2024-04-07 16:11:32,940 [DEBUG] MainProcess(17340):MainThread        (6296 ) | emailall.run:69 - [*] Starting EmailAll @ 2024-04-07 16:11:32

2024-04-07 16:11:32,941 [INFOR] MainProcess(17340):MainThread        (6296 ) | utils.get_net_env:44 - Checking network environment
2024-04-07 16:11:32,941 [DEBUG] MainProcess(17340):MainThread        (6296 ) | utils.check_net:24 - Trying to access http://ip-api.com/json/
2024-04-07 16:11:33,582 [DEBUG] MainProcess(17340):MainThread        (6296 ) | utils.check_net:33 - Access to Internet OK
2024-04-07 16:11:33,584 [DEBUG] MainProcess(17340):MainThread        (6296 ) | utils.check_net:39 - The computer is not located in China
2024-04-07 16:11:33,586 [DEBUG] MainProcess(17340):MainThread        (6296 ) | utils.get_domains:101 - Getting domains
2024-04-07 16:11:33,588 [DEBUG] MainProcess(17340):MainThread        (6296 ) | utils.get_domains:109 - The obtained domains 
['transformice.com']
2024-04-07 16:11:33,590 [INFOR] MainProcess(17340):MainThread        (6296 ) | collect.run:45 - Start collecting Emails of transformice.com
2024-04-07 16:11:34,143 [INFOR] MainProcess(17340):Emailf            (17076) | module.begin:57 - Start Email-Format module to collect Emaile of transformice.com
2024-04-07 16:11:34,148 [INFOR] MainProcess(17340):phonebook         (7336 ) | module.begin:57 - Start PhoneBook module to collect Emaile of transformice.com
2024-04-07 16:11:34,150 [INFOR] MainProcess(17340):skymem            (5468 ) | module.begin:57 - Start Skymem module to collect Emaile of transformice.com
2024-04-07 16:11:34,155 [INFOR] MainProcess(17340):snov              (14516) | module.begin:57 - Start Snov module to collect Emaile of transformice.com
2024-04-07 16:11:34,156 [INFOR] MainProcess(17340):veryvp            (10712) | module.begin:57 - Start Veryvp module to collect Emaile of transformice.com
2024-04-07 16:11:34,160 [INFOR] MainProcess(17340):ask               (4320 ) | module.begin:57 - Start AskSearch module to collect Emaile of transformice.com
2024-04-07 16:11:34,170 [INFOR] MainProcess(17340):baidu             (4032 ) | module.begin:57 - Start BaiduSearch module to collect Emaile of transformice.com
2024-04-07 16:11:34,173 [INFOR] MainProcess(17340):bingcn            (10352) | module.begin:57 - Start BingcnSearch module to collect Emaile of transformice.com
2024-04-07 16:11:34,196 [INFOR] MainProcess(17340):githubapi         (10004) | module.begin:57 - Start GithubApi module to collect Emaile of transformice.com
2024-04-07 16:11:34,199 [INFOR] MainProcess(17340):google            (15584) | module.begin:57 - Start GoogleSearch module to collect Emaile of transformice.com
2024-04-07 16:11:34,203 [INFOR] MainProcess(17340):qwant             (12516) | module.begin:57 - Start QwantSearch module to collect Emaile of transformice.com
2024-04-07 16:11:34,220 [INFOR] MainProcess(17340):so                (2280 ) | module.begin:57 - Start SoSearch module to collect Emaile of transformice.com
2024-04-07 16:11:34,228 [INFOR] MainProcess(17340):sogou             (13764) | module.begin:57 - Start SogouSearch module to collect Emaile of transformice.com
2024-04-07 16:11:34,369 [ERROR] MainProcess(17340):phonebook         (7336 ) | module.post:132 - HTTPSConnectionPool(host='public.intelx.io', port=443): Max retries exceeded with url: /phonebook/search?k=077424c6-7a26-410e-9269-c9ac546886a4 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024E3557F750>: Failed to resolve 'public.intelx.io' ([Errno 11001] getaddrinfo failed)"))
2024-04-07 16:11:34,402 [DEBUG] MainProcess(17340):phonebook         (7336 ) | module.finish:66 - Finished PhoneBook module to collect transformice.com's Email
2024-04-07 16:11:34,403 [INFOR] MainProcess(17340):phonebook         (7336 ) | module.finish:68 - PhoneBook module took 0.3 seconds found 0 Email
2024-04-07 16:11:35,301 [DEBUG] MainProcess(17340):Emailf            (17076) | module.finish:66 - Finished Email-Format module to collect transformice.com's Email
2024-04-07 16:11:35,302 [INFOR] MainProcess(17340):Emailf            (17076) | module.finish:68 - Email-Format module took 1.2 seconds found 2 Email
2024-04-07 16:11:36,258 [ERROR] MainProcess(17340):google            (15584) | module.get:102 - HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024E355A2890>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión')))
2024-04-07 16:11:36,260 [ERROR] MainProcess(17340):google            (15584) | google.search:41 - For module GoogleSearch, you need to configure the proxy in setting.py file
2024-04-07 16:11:36,263 [DEBUG] MainProcess(17340):google            (15584) | module.finish:66 - Finished GoogleSearch module to collect transformice.com's Email
2024-04-07 16:11:36,265 [INFOR] MainProcess(17340):google            (15584) | module.finish:68 - GoogleSearch module took 2.1 seconds found 0 Email
2024-04-07 16:11:37,568 [ALERT] MainProcess(17340):qwant             (12516) | utils.check_response:123 - GET https://api.qwant.com/v3/search/web?q=%40transformice.com&count=10&locale=zh_CN&offset=0&device=desktop&safesearch=1 403 - Forbidden 677
2024-04-07 16:11:37,569 [ALERT] MainProcess(17340):qwant             (12516) | utils.check_response:132 - {'status': 'error', 'data': {'error_data': {'captchaUrl': 'https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAxe8DESTDneQAyfGjlQ==&cid=5NbOoCNbQ6NPSjBRwREHsAuMXlhL4YCG0Km7DCtCYiiaiyQ1~VnJnfcxzBI6HH3Xuv2Rpz_rWkRM2OvJEHJmf2RNcj837Sk84R_09DDUaahxCIGvErfml1~qr2ZoFXdC&referer=http%3A%2F%2Fapi.qwant.com%2Fv3%2Fsearch%2Fweb%3Fq%3Dbd7d885322ca359607a9ee206d649b45f5555f98c025442c5f9eec37f7da445c528e5499261dbfe91cfaea17219d8e995f7e50278d0c2e31b7def0089f3ef6fd%26count%3D10%26locale%3Dzh_CN%26offset%3D0%26device%3Ddesktop%26safesearch%3D1&hash=78B13B7513D180B7AB6D6FF9EB0A51&t=fe&s=43332&e=18fa10df7a8f755df45898f3e9f007a49a2cc4f49344197b2be514d6e4325ee3'}, 'error_code': 27}}
2024-04-07 16:11:37,572 [DEBUG] MainProcess(17340):qwant             (12516) | module.finish:66 - Finished QwantSearch module to collect transformice.com's Email
2024-04-07 16:11:37,572 [INFOR] MainProcess(17340):qwant             (12516) | module.finish:68 - QwantSearch module took 3.4 seconds found 0 Email
2024-04-07 16:11:38,221 [ERROR] MainProcess(17340):ask               (4320 ) | module.get:102 - HTTPSConnectionPool(host='www.ask.com', port=443): Max retries exceeded with url: /web?q=intext%3A%40transformice.com&page=1 (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024E35569D50>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión')))
2024-04-07 16:11:38,223 [ERROR] MainProcess(17340):ask               (4320 ) | ask.search:44 - For module AskSearch, you need to configure the proxy in setting.py file
2024-04-07 16:11:38,225 [DEBUG] MainProcess(17340):ask               (4320 ) | module.finish:66 - Finished AskSearch module to collect transformice.com's Email
2024-04-07 16:11:38,225 [INFOR] MainProcess(17340):ask               (4320 ) | module.finish:68 - AskSearch module took 4.1 seconds found 0 Email
2024-04-07 16:11:38,793 [DEBUG] MainProcess(17340):bingcn            (10352) | module.finish:66 - Finished BingcnSearch module to collect transformice.com's Email
2024-04-07 16:11:38,794 [INFOR] MainProcess(17340):bingcn            (10352) | module.finish:68 - BingcnSearch module took 4.6 seconds found 0 Email
2024-04-07 16:11:39,129 [DEBUG] MainProcess(17340):baidu             (4032 ) | module.finish:66 - Finished BaiduSearch module to collect transformice.com's Email
2024-04-07 16:11:39,130 [INFOR] MainProcess(17340):baidu             (4032 ) | module.finish:68 - BaiduSearch module took 5.0 seconds found 0 Email
2024-04-07 16:11:39,758 [ERROR] MainProcess(17340):veryvp            (10712) | module.post:132 - HTTPConnectionPool(host='veryvp.com', port=80): Max retries exceeded with url: /user/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000024E3558C710>, 'Connection to veryvp.com timed out. (connect timeout=5)'))
2024-04-07 16:11:40,769 [ALERT] MainProcess(17340):githubapi         (10004) | utils.check_response:123 - GET https://api.github.com/search/code?q=transformice.com&per_page=100&page=1&sort=indexed&access_token= 401 - Unauthorized 90
2024-04-07 16:11:40,772 [ALERT] MainProcess(17340):githubapi         (10004) | utils.check_response:132 - {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}
2024-04-07 16:11:40,779 [ALERT] MainProcess(17340):githubapi         (10004) | githubapi.search:72 - 'NoneType' object has no attribute 'json'
2024-04-07 16:11:40,782 [DEBUG] MainProcess(17340):githubapi         (10004) | module.finish:66 - Finished GithubApi module to collect transformice.com's Email
2024-04-07 16:11:40,784 [INFOR] MainProcess(17340):githubapi         (10004) | module.finish:68 - GithubApi module took 6.6 seconds found 0 Email
2024-04-07 16:11:41,535 [DEBUG] MainProcess(17340):sogou             (13764) | module.finish:66 - Finished SogouSearch module to collect transformice.com's Email
2024-04-07 16:11:41,536 [INFOR] MainProcess(17340):sogou             (13764) | module.finish:68 - SogouSearch module took 7.3 seconds found 0 Email
2024-04-07 16:11:44,359 [DEBUG] MainProcess(17340):so                (2280 ) | module.finish:66 - Finished SoSearch module to collect transformice.com's Email
2024-04-07 16:11:44,359 [INFOR] MainProcess(17340):so                (2280 ) | module.finish:68 - SoSearch module took 10.1 seconds found 0 Email
2024-04-28 23:13:41,331 [DEBUG] MainProcess(8536):MainThread        (7444 ) | emailall.run:69 - [*] Starting EmailAll @ 2024-04-28 23:13:41

2024-04-28 23:13:41,331 [INFOR] MainProcess(8536):MainThread        (7444 ) | utils.get_net_env:44 - Checking network environment
2024-04-28 23:13:41,332 [DEBUG] MainProcess(8536):MainThread        (7444 ) | utils.check_net:24 - Trying to access http://ip-api.com/json/
2024-04-28 23:13:41,711 [DEBUG] MainProcess(8536):MainThread        (7444 ) | utils.check_net:33 - Access to Internet OK
2024-04-28 23:13:41,712 [DEBUG] MainProcess(8536):MainThread        (7444 ) | utils.check_net:39 - The computer is not located in China
2024-04-28 23:13:41,713 [DEBUG] MainProcess(8536):MainThread        (7444 ) | utils.get_domains:101 - Getting domains
2024-04-28 23:13:41,713 [DEBUG] MainProcess(8536):MainThread        (7444 ) | utils.get_domains:109 - The obtained domains 
['transformice.com']
2024-04-28 23:13:41,714 [INFOR] MainProcess(8536):MainThread        (7444 ) | collect.run:45 - Start collecting Emails of transformice.com
2024-04-28 23:13:41,876 [INFOR] MainProcess(8536):Emailf            (13796) | module.begin:57 - Start Email-Format module to collect Emaile of transformice.com
2024-04-28 23:13:41,879 [INFOR] MainProcess(8536):phonebook         (13168) | module.begin:57 - Start PhoneBook module to collect Emaile of transformice.com
2024-04-28 23:13:41,883 [INFOR] MainProcess(8536):skymem            (15540) | module.begin:57 - Start Skymem module to collect Emaile of transformice.com
2024-04-28 23:13:41,885 [INFOR] MainProcess(8536):snov              (13892) | module.begin:57 - Start Snov module to collect Emaile of transformice.com
2024-04-28 23:13:41,886 [INFOR] MainProcess(8536):veryvp            (12144) | module.begin:57 - Start Veryvp module to collect Emaile of transformice.com
2024-04-28 23:13:41,888 [INFOR] MainProcess(8536):ask               (10556) | module.begin:57 - Start AskSearch module to collect Emaile of transformice.com
2024-04-28 23:13:41,889 [INFOR] MainProcess(8536):baidu             (8348 ) | module.begin:57 - Start BaiduSearch module to collect Emaile of transformice.com
2024-04-28 23:13:41,891 [INFOR] MainProcess(8536):bingcn            (9420 ) | module.begin:57 - Start BingcnSearch module to collect Emaile of transformice.com
2024-04-28 23:13:41,893 [INFOR] MainProcess(8536):githubapi         (13948) | module.begin:57 - Start GithubApi module to collect Emaile of transformice.com
2024-04-28 23:13:41,894 [INFOR] MainProcess(8536):google            (3400 ) | module.begin:57 - Start GoogleSearch module to collect Emaile of transformice.com
2024-04-28 23:13:41,898 [INFOR] MainProcess(8536):qwant             (13404) | module.begin:57 - Start QwantSearch module to collect Emaile of transformice.com
2024-04-28 23:13:41,902 [INFOR] MainProcess(8536):so                (8812 ) | module.begin:57 - Start SoSearch module to collect Emaile of transformice.com
2024-04-28 23:13:41,905 [INFOR] MainProcess(8536):sogou             (12532) | module.begin:57 - Start SogouSearch module to collect Emaile of transformice.com
2024-04-28 23:13:41,931 [ERROR] MainProcess(8536):phonebook         (13168) | module.post:132 - HTTPSConnectionPool(host='public.intelx.io', port=443): Max retries exceeded with url: /phonebook/search?k=077424c6-7a26-410e-9269-c9ac546886a4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014E23BD2FD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2024-04-28 23:13:41,934 [DEBUG] MainProcess(8536):phonebook         (13168) | module.finish:66 - Finished PhoneBook module to collect transformice.com's Email
2024-04-28 23:13:41,934 [INFOR] MainProcess(8536):phonebook         (13168) | module.finish:68 - PhoneBook module took 0.1 seconds found 0 Email
2024-04-28 23:13:43,154 [DEBUG] MainProcess(8536):Emailf            (13796) | module.finish:66 - Finished Email-Format module to collect transformice.com's Email
2024-04-28 23:13:43,154 [INFOR] MainProcess(8536):Emailf            (13796) | module.finish:68 - Email-Format module took 1.3 seconds found 2 Email
2024-04-28 23:13:43,967 [ERROR] MainProcess(8536):google            (3400 ) | module.get:102 - HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014E23C48290>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión')))
2024-04-28 23:13:43,968 [ERROR] MainProcess(8536):google            (3400 ) | google.search:41 - For module GoogleSearch, you need to configure the proxy in setting.py file
2024-04-28 23:13:43,968 [DEBUG] MainProcess(8536):google            (3400 ) | module.finish:66 - Finished GoogleSearch module to collect transformice.com's Email
2024-04-28 23:13:43,969 [INFOR] MainProcess(8536):google            (3400 ) | module.finish:68 - GoogleSearch module took 2.1 seconds found 0 Email
2024-04-28 23:13:44,813 [ALERT] MainProcess(8536):qwant             (13404) | utils.check_response:123 - GET https://api.qwant.com/v3/search/web?q=%40transformice.com&count=10&locale=zh_CN&offset=0&device=desktop&safesearch=1 403 - Forbidden 677
2024-04-28 23:13:44,813 [ALERT] MainProcess(8536):qwant             (13404) | utils.check_response:132 - {'status': 'error', 'data': {'error_data': {'captchaUrl': 'https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAyE1cucUjIk8AybzsiA==&cid=0pSpvRb~scbyyAMJVDXXaRUkNWJ5IHyu6fhWQ~BixEKEd9~uui9Y~ZPRolrb16UB47WGO1_rEHsGB_xTM7I_YlIfWMbdbNYOdhpVX2EqfG5HWcEZLC1UpnhAoJ7cpqHO&referer=http%3A%2F%2Ffdn.qwant.com%2Fv3%2Fsearch%2Fweb%3Fq%3D3a6a3703035072cc9475b50338ad38af8e97c2ca150cc267f805a84dc428e244ec39bdde0da14b6f24800cc627e5711170f6f3ab55676c5d353f3378d88a15bb%26count%3D10%26locale%3Dzh_CN%26offset%3D0%26device%3Ddesktop%26safesearch%3D1&hash=78B13B7513D180B7AB6D6FF9EB0A51&t=fe&s=43332&e=639f37f351a8ae13c29c81292992e54656272d0dd9a13e9902751ada2dac3cec'}, 'error_code': 27}}
2024-04-28 23:13:44,815 [DEBUG] MainProcess(8536):qwant             (13404) | module.finish:66 - Finished QwantSearch module to collect transformice.com's Email
2024-04-28 23:13:44,815 [INFOR] MainProcess(8536):qwant             (13404) | module.finish:68 - QwantSearch module took 2.9 seconds found 0 Email
2024-04-28 23:13:45,544 [DEBUG] MainProcess(8536):bingcn            (9420 ) | module.finish:66 - Finished BingcnSearch module to collect transformice.com's Email
2024-04-28 23:13:45,545 [INFOR] MainProcess(8536):bingcn            (9420 ) | module.finish:68 - BingcnSearch module took 3.7 seconds found 0 Email
2024-04-28 23:13:45,933 [ERROR] MainProcess(8536):ask               (10556) | module.get:102 - HTTPSConnectionPool(host='www.ask.com', port=443): Max retries exceeded with url: /web?q=intext%3A%40transformice.com&page=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014E23BD3890>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión')))
2024-04-28 23:13:45,934 [ERROR] MainProcess(8536):ask               (10556) | ask.search:44 - For module AskSearch, you need to configure the proxy in setting.py file
2024-04-28 23:13:45,934 [DEBUG] MainProcess(8536):ask               (10556) | module.finish:66 - Finished AskSearch module to collect transformice.com's Email
2024-04-28 23:13:45,935 [INFOR] MainProcess(8536):ask               (10556) | module.finish:68 - AskSearch module took 4.0 seconds found 0 Email
2024-04-28 23:13:46,625 [DEBUG] MainProcess(8536):baidu             (8348 ) | module.finish:66 - Finished BaiduSearch module to collect transformice.com's Email
2024-04-28 23:13:46,626 [INFOR] MainProcess(8536):baidu             (8348 ) | module.finish:68 - BaiduSearch module took 4.7 seconds found 0 Email
2024-04-28 23:13:47,526 [ERROR] MainProcess(8536):veryvp            (12144) | module.post:132 - HTTPConnectionPool(host='veryvp.com', port=80): Max retries exceeded with url: /user/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000014E23C35F10>, 'Connection to veryvp.com timed out. (connect timeout=5)'))
2024-04-28 23:13:48,276 [ALERT] MainProcess(8536):githubapi         (13948) | utils.check_response:123 - GET https://api.github.com/search/code?q=transformice.com&per_page=100&page=1&sort=indexed&access_token= 401 - Unauthorized 90
2024-04-28 23:13:48,277 [ALERT] MainProcess(8536):githubapi         (13948) | utils.check_response:132 - {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}
2024-04-28 23:13:48,279 [ALERT] MainProcess(8536):githubapi         (13948) | githubapi.search:72 - 'NoneType' object has no attribute 'json'
2024-04-28 23:13:48,280 [DEBUG] MainProcess(8536):githubapi         (13948) | module.finish:66 - Finished GithubApi module to collect transformice.com's Email
2024-04-28 23:13:48,281 [INFOR] MainProcess(8536):githubapi         (13948) | module.finish:68 - GithubApi module took 6.4 seconds found 0 Email
2024-04-28 23:13:48,851 [DEBUG] MainProcess(8536):sogou             (12532) | module.finish:66 - Finished SogouSearch module to collect transformice.com's Email
2024-04-28 23:13:48,851 [INFOR] MainProcess(8536):sogou             (12532) | module.finish:68 - SogouSearch module took 6.9 seconds found 0 Email
2024-04-28 23:13:50,854 [DEBUG] MainProcess(8536):so                (8812 ) | module.finish:66 - Finished SoSearch module to collect transformice.com's Email
2024-04-28 23:13:50,855 [INFOR] MainProcess(8536):so                (8812 ) | module.finish:68 - SoSearch module took 9.0 seconds found 0 Email
